spring.application.name=ApiGateway

server.port=9090

eureka.client.service-url.defaultzone=http://localhost:8761/eureka

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n


spring.cloud.gateway.server.webflux.routes[0].id=AUTHSERVICE
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=PRODUCTSERVICE
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/product/**

spring.cloud.gateway.server.webflux.routes[2].id=INVENTORYSERVICE
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/inventory/**

spring.cloud.gateway.server.webflux.routes[3].id=ORDERSERVICE
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/order/**

spring.cloud.gateway.server.webflux.routes[4].id=PAYMENTSERVICE
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8085
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/payment/**

spring.cloud.gateway.server.webflux.routes[5].id=NOTIFICATIONSERVICE
spring.cloud.gateway.server.webflux.routes[5].uri=http://localhost:8086
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/notification/**